title: Daniel Althoff # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Brazilian, 28 y/o
  <br><br>
  M.Sc. in Agricultural Engineering  
  <br><br>
  <a href="https://www.linkedin.com/in/daniel-althoff-b1091a24/" target='blank'>LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.researchgate.net/profile/Daniel_Althoff" target='blank'>ResearchGate Profile</a> 
  
theme: jekyll-theme-minimal
##google_analytics: UA-000000-0 # your Google Analytics tracking ID here
